pipeline {
  agent any
  stages {
    stage('Pre-Staging') {
      steps {
        sh 'pwd'
        sh 'ls -lahrt'
        sh 'ls -lahrt ELK-project/infrastructure/jenkins'
        sh 'ls -lahrt ELK-project/infrastructure/ansible'
      }
    }

  }
}